Algoritmo "PARouIMPAR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : verdadeiro ou falso
// Autor(a)    :Dante
// Data atual  : 19/01/2022
var
   N: Inteiro
inicio
      Escreva("DIGITE UM NUMERO QUALQUER: ")
      Leia(N)
      Se (N % 2 = 0) entao
         Escreval("O numero " , N, " e PAR ")
      Senao
           Escreval("O numero ", N, " e IMPAR ")
      FimSe
fimalgoritmo