Algoritmo "DOLAR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/01/2022
Var
   reais, dolares: Real

Inicio
   escreva("Quantos reais eu tenho? R$" )
   Leia(reais)
   dolares <- reais/ 5,4977
   escreva("Posso ter US$" , dolares)

Fimalgoritmo