Algoritmo "PAR OU IMPAR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Par ou impar
// Autor(a)    : Dante
// Data atual  : 05/03/2022
Var
// Seção de Declarações das variáveis 
   escreva ("Digite um número qualquer: ")
        leia (num)
     se (num % 2 = 0) entao
   escreva ("O número", num," é PAR")
        senao
     escreva ("O número", num," é ÍMPAR")
     fimse

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo