Algoritmo "Salario"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   :Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//                   final uma mensagem.
// Autor(a)    :Dante
// Data atual  : 18/01/2022
Var
 Nome: caractere
 N1: Inteiro

Inicio
 Escreva("Nome do funcionario:")
 Leia(Nome)
 Escreva("Salario:")
 Leia (N1)
 Escreva("O funcionario(a) ", Nome, " tem um salario de ", N1, " em Junho ")


Fimalgoritmo